# Generated by Django 5.0.6 on 2024-09-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletFundings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('fund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settle_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('header', models.CharField(max_length=255)),
                ('transaction_reference', models.CharField(max_length=255, unique=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desciption', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WalletFunding',
        ),
    ]
