# Generated by Django 5.0.6 on 2024-09-19 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_walletfundings_delete_walletfunding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title1', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title2', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title3', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title4', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title5', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('sub_content1', models.TextField(blank=True, null=True)),
                ('sub_content2', models.TextField(blank=True, null=True)),
                ('sub_content3', models.TextField(blank=True, null=True)),
                ('sub_content4', models.TextField(blank=True, null=True)),
                ('sub_content5', models.TextField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('images', models.ImageField(upload_to='static')),
                ('pre_image', models.ImageField(upload_to='static')),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
