# Generated by Django 5.0.6 on 2024-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='random_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
